export const CHARACTER_CSS=`.gk-character{width:var(--size);height:var(--size)}.sample small{width:auto;text-align:center;font-size:9px}.live{font-size:11px;color:#6f766c;min-width:150px}
.gk-character{width:var(--size,56px);height:var(--size,56px);display:inline-block;flex:none;overflow:visible}.gk-character svg{display:block;width:100%;height:100%;overflow:visible}.body,.eyes,.blink,.hand,.ground,.signal{transform-box:view-box;transform-origin:32px 48px}.eyes{transform-origin:32px 32px}.blink{transform-origin:32px 31px}.hand{opacity:0;transform-origin:32px 42px}.ground{opacity:.09;transform-origin:32px 57px}.signal{opacity:0;transform-origin:52px 14px}.gk-character[data-state=idle] .blink{animation:gkc-blink 6.7s infinite}.gk-character[data-state=idle] .body{animation:gkc-settle 7s ease-in-out infinite}.gk-character[data-state=active] .body{animation:gkc-ponder 3.1s ease-in-out infinite}.gk-character[data-state=active] .eyes{animation:gkc-look 3.1s ease-in-out infinite}.gk-character[data-state=active] .blink{animation:gkc-blink 4.3s infinite}.gk-character[data-state=working] .body{animation:gkc-work var(--pace,1.6s) ease-in-out infinite}.gk-character[data-state=working] .eyes{animation:gkc-scan 2s ease-in-out infinite}.gk-character[data-state=working] .hand{opacity:1;animation:gkc-tap .48s ease-in-out infinite alternate}.gk-character[data-state=working] .hand.right{animation-delay:-.35s}.gk-character[data-personality=architect][data-state=working] .body{animation:gkc-ponder 2.6s ease-in-out infinite}.gk-character[data-personality=qa][data-state=working] .eyes{animation:gkc-scan .95s ease-in-out infinite}.gk-character[data-personality=chief][data-state=working] .body{animation:gkc-coordinate 2.3s ease-in-out infinite}.gk-character[data-state=waiting] .body{animation:gkc-attend 6s ease-in-out 1}.gk-character[data-state=waiting] .signal{opacity:1}.gk-character[data-state=waiting] .blink{animation:gkc-blink 5s infinite}.gk-character[data-state=done] .body{animation:gkc-celebrate 1.05s ease-out 1}.gk-character[data-state=done] .signal{opacity:1}.gk-character[data-state=error] .body{animation:gkc-shake .5s ease-out 1}.gk-character[data-state=error] .signal{opacity:1}.gk-character[data-state=paused] .eyes{transform:translateY(2px) scaleY(.55)}.gk-character[data-state=paused] .body{transform:translateY(2px)}.gk-character[data-state=unknown] svg{opacity:.6}.gk-character[data-state=unused-gkc-greet] .body{animation:gkc-greet 1.15s ease-out 1}.gk-character[data-state=unused-gkc-greet] .hand.right{opacity:1;animation:gkc-wave 1.15s ease-out 1}.gk-character[data-surface=small] .hand,.gk-character[data-surface=small] .ground{display:none}.gk-character[data-surface=small] .signal{transform:scale(.8)}
@keyframes gkc-blink{0%,40%,44%,100%{transform:scaleY(1)}42%{transform:scaleY(.08)}}@keyframes gkc-settle{0%,63%,100%{transform:none}68%{transform:translateY(-1.5px) scale(1.02,.98)}74%{transform:none}}@keyframes gkc-ponder{0%,100%{transform:rotate(0)}25%,65%{transform:rotate(-9deg) translateY(-2px)}80%{transform:rotate(3deg)}}@keyframes gkc-look{0%,100%{transform:none}25%,65%{transform:translate(3px,-3px)}80%{transform:translate(-2px,0)}}@keyframes gkc-scan{0%,100%{transform:translate(-3px,1px)}50%{transform:translate(3px,1px)}}@keyframes gkc-work{0%,100%{transform:translateY(1px) scale(1.04,.96)}25%{transform:translate(-2px,-3px) rotate(-5deg)}50%{transform:translateY(1px) scale(1.04,.96)}75%{transform:translate(2px,-3px) rotate(5deg)}}@keyframes gkc-coordinate{0%,100%{transform:none}20%{transform:rotate(-8deg)}40%{transform:none}65%{transform:rotate(8deg) translateY(-2px)}80%{transform:scale(1.06,.94)}}@keyframes gkc-tap{from{transform:translateY(2px)}to{transform:translateY(-4px)}}@keyframes gkc-attend{0%,10%,100%{transform:none}3%,7%{transform:translateY(-4px) rotate(5deg)}5%{transform:none}}@keyframes gkc-celebrate{0%{transform:none}15%{transform:scale(1.15,.85)}45%{transform:translateY(-11px) rotate(-10deg) scale(.94,1.06)}70%{transform:translateY(1px) scale(1.13,.87)}85%{transform:translateY(-3px)}100%{transform:none}}@keyframes gkc-shake{0%,100%{transform:none}20%,60%{transform:translateX(-4px) rotate(-5deg)}40%,80%{transform:translateX(4px) rotate(5deg)}}@keyframes gkc-greet{0%,100%{transform:none}30%{transform:translateY(-5px) rotate(-8deg)}65%{transform:rotate(6deg)}}@keyframes gkc-wave{0%,100%{transform:none}25%,65%{transform:translateY(-12px) rotate(-14deg)}45%,80%{transform:translateY(-9px) rotate(4deg)}}

.gk-character{flex:none;overflow:visible;display:inline-flex}.gk-character .blink{animation-delay:var(--blink-delay,0s)!important}
.gk-character[data-state=active] .hand{display:none}
.gk-character[data-state=error][data-event=false] .body{animation:none}
.gk-character[data-static=true] *{animation:none!important}
.gk-character[data-quiet=true] .body{animation:none!important}.gk-character[data-quiet=true] .hand{display:none}
.gk-character[data-motion=quiet] .body,.gk-character[data-motion=quiet] .hand{animation:none!important}
@media(prefers-reduced-motion:reduce){.gk-character *{animation:none!important}.gk-character .hand{display:none}}
.gk-motion-setting{display:flex;align-items:center;flex-wrap:wrap;gap:14px;font-size:14px;padding:22px 0;border-top:1px solid var(--gk-line)}.gk-motion-setting select{font:inherit;min-height:40px;border:1px solid var(--gk-line);border-radius:8px;padding:6px 12px;color:inherit;background:var(--gk-bg)}.gk-motion-setting small{flex-basis:100%;font-size:12px;color:var(--gk-text-2)}
`
