// Shared application typography and interaction scale.
export const UX_CSS=`
:root{--gk-font-meta:12px;--gk-font-label:14px;--gk-font-body:15px;--gk-font-title:18px;--gk-font-display:26px;--gk-text-2:#62626b;--gk-text-3:#73737c}
.grokbot-chat{position:relative}
.gk-profile-overlay{position:absolute;inset:76px 0 0;z-index:40;display:flex;align-items:flex-start;justify-content:center;padding:20px;background:rgba(247,247,247,.94);overflow:auto}
.gk-profile-form button{font:inherit;font-size:var(--gk-font-label);min-height:40px;padding:8px 14px;border:1px solid var(--gk-line);border-radius:10px;background:var(--gk-bg);cursor:pointer}.gk-profile-form button.grokbot-form__submit{background:var(--gk-text);color:var(--gk-bg)}
.grokbot-chat,.grokbot-sidebar,.gk-board,.gk-work{font-size:var(--gk-font-body);line-height:1.55}
.grokbot-log{overflow-anchor:none;overscroll-behavior:contain;scroll-behavior:auto;scrollbar-gutter:stable}
.grokbot-log pre{overscroll-behavior:auto}
.grokbot-chat__head{min-height:76px;gap:14px}
.grokbot-chat__name{font-size:var(--gk-font-title)}
.grokbot-chat__close,.grokbot-iconbtn,.gk-board-toggle{min-width:44px;min-height:44px;border-radius:12px}
.gk-board-toggle{font:inherit;font-size:var(--gk-font-label);padding:8px 14px;background:var(--gk-bg-soft);border:1px solid var(--gk-line);color:var(--gk-text);cursor:pointer;white-space:nowrap}
.gkf-row{min-height:72px;gap:12px;padding:10px 12px}
.gk-profile-form{box-sizing:border-box;width:min(620px,100%);max-width:620px;margin:12px auto;padding:24px!important;border:1px solid var(--gk-line);border-radius:18px;background:var(--gk-bg);max-height:100%;overflow:auto;box-shadow:0 8px 32px #00000008}
.gk-profile-form header strong{font-size:var(--gk-font-title)}.gk-profile-form header p{color:var(--gk-text-2);margin:6px 0 18px;font-size:var(--gk-font-label)}
.gk-profile-form>label{font-size:var(--gk-font-label);font-weight:600;margin-top:12px}.gk-profile-form input,.gk-profile-form select{min-height:44px}.gk-profile-form textarea{min-height:130px}.gk-profile-form .grokbot-form__actions{position:sticky;bottom:-24px;background:var(--gk-bg);padding-bottom:16px;z-index:2;margin-top:16px;padding-top:16px;border-top:1px solid var(--gk-line)}
.gk-work{background:var(--gk-bg);scrollbar-width:thin}.gk-work>button{min-height:36px;font:inherit;font-weight:600}.gk-work small{font-size:var(--gk-font-meta);color:var(--gk-text-2)}.gk-work summary{cursor:pointer;padding:8px 0;font-size:var(--gk-font-label)}.gk-work p{font-size:var(--gk-font-label);line-height:1.65}.gk-work pre{font-size:var(--gk-font-meta)}
.gk-execution{margin-top:16px;border-left:2px solid var(--gk-line);padding-left:16px}.gk-execution h4{margin:0 0 12px;font-size:var(--gk-font-label)}.gk-execution time{font-size:var(--gk-font-meta);color:var(--gk-text-2)}.gk-execution__tool{border:1px solid var(--gk-line);border-radius:12px;margin:10px 0;background:var(--gk-bg-soft);padding:4px 12px}.gk-execution__tool summary{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.gk-execution__state{margin-left:auto;color:var(--gk-text-2);font-size:var(--gk-font-meta)}.gk-execution pre{max-height:340px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;background:var(--gk-bg);padding:12px;border-radius:8px}.gk-execution__progress p{white-space:pre-wrap;overflow-wrap:anywhere;margin-top:4px}
 .gk-shot{position:relative;flex:none}.gk-shot-menu{position:absolute;bottom:48px;left:0;width:280px;padding:12px;background:var(--gk-bg);border:1px solid var(--gk-line);border-radius:16px;box-shadow:0 12px 40px #00000020;z-index:60;color:var(--gk-text)}.gk-shot-menu>strong{display:block;padding:4px 10px 8px;font-size:14px}.gk-shot-menu button{display:flex;flex-direction:column;gap:3px;width:100%;border:0;background:transparent;border-radius:10px;padding:10px;text-align:left;cursor:pointer;color:inherit;font:inherit;font-size:14px}.gk-shot-menu button:hover,.gk-shot-menu button:focus-visible{background:var(--gk-bg-soft)}.gk-shot-menu small,.gk-shot-menu p{font-size:12px;color:var(--gk-text-2);line-height:1.6}.gk-shot-menu p{margin:8px 10px 4px;border-top:1px solid var(--gk-line);padding-top:12px}.gk-shot-menu kbd{font:inherit;font-weight:600;color:var(--gk-text)}.gk-shot-status{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 14px;font-size:13px;border-radius:12px;background:var(--gk-bg-soft);margin-bottom:8px}.gk-shot-status button{font:inherit;border:0;background:transparent;cursor:pointer;min-height:32px}.gk-shot-error{font-size:13px;color:#a32929}

.gk-capture-button{flex:none;width:36px;height:36px;background:transparent;border:0;border-radius:9px;color:var(--gk-text-2);cursor:pointer;display:grid;place-items:center}.gk-capture-button:hover{background:var(--gk-bg-soft)}.gk-capture-button:disabled{opacity:.4}.gk-capture-preview{display:flex;gap:12px;align-items:center;flex-wrap:wrap;padding:8px 0}.gk-capture-preview figure{margin:0;display:flex;gap:8px;align-items:center}.gk-capture-preview img{width:100px;height:70px;object-fit:contain;border:1px solid var(--gk-line);border-radius:8px}.gk-capture-preview span{font-size:var(--gk-font-meta);color:var(--gk-text-2)}.gk-capture-preview button{font:inherit;font-size:var(--gk-font-meta);background:transparent;border:0;cursor:pointer;min-height:36px}
.gkf-composer__plus:disabled{display:none}.gkf-composer__send{width:36px;height:36px}.gkf-composer__input{min-width:0}
.grokbot-chat :focus-visible,.gkf-row:focus-visible{outline:2px solid var(--gk-accent);outline-offset:3px}
.gkf-composer{flex-shrink:0;padding:12px 20px 16px}
.gkf-composer__pill{display:flex;flex-direction:column;align-items:stretch;gap:8px;border-radius:20px;padding:14px 14px 8px;background:var(--gk-bg);border:1px solid var(--gk-line);box-shadow:0 2px 8px #00000005}
.gkf-composer__pill:focus-within{border-color:#94949c;box-shadow:0 0 0 2px #73737c18}
.grokbot-chat .gkf-composer__input,.grokbot-chat .gkf-composer__input:focus-visible{box-sizing:border-box;display:block;flex:none;width:100%;min-width:0;min-height:56px;max-height:200px;padding:2px 4px;border:0;border-radius:0;outline:none;box-shadow:none;font:inherit;font-size:15px;line-height:24px;resize:none;overflow-y:auto;background:transparent}
.gkf-composer__toolbar{display:flex;align-items:center;gap:8px;min-height:44px}
.gkf-composer__hint{flex:1;font-size:12px;color:var(--gk-text-2);padding:0 4px}
.gkf-composer__send,.gkf-composer__plus,.gk-capture-button{width:44px;height:44px}
.gk-capture-preview{padding:0 4px;max-height:150px;overflow:auto}
@media(max-width:600px){.gkf-composer{padding:8px 12px 12px}.gkf-composer__hint{font-size:12px}.gk-shot-menu{width:min(280px,70vw)}}

.grokbot-home{display:block!important;box-sizing:border-box;overflow:auto;min-height:100%;padding:clamp(60px,10vh,120px) clamp(28px,6vw,96px) 72px;background:var(--gk-bg)!important;text-align:left}
.grokbot-home__content{max-width:690px;margin:0 auto}.grokbot-home__eyebrow{font-size:11px;font-weight:600;letter-spacing:3.5px;color:var(--gk-text-2)}
.grokbot-home .grokbot-home__title{font-size:clamp(28px,2.6vw,36px);font-weight:600;letter-spacing:-1px;line-height:1.3;margin:22px 0 15px;text-align:left}
.grokbot-home .grokbot-home__sub{font-size:17px;color:var(--gk-text-2);margin:0 0 44px;line-height:1.6}
.grokbot-home__chief{display:flex;align-items:center;gap:20px;padding:14px 0 28px;width:100%;border:0;border-bottom:1px solid var(--gk-line);background:transparent;color:inherit;text-align:left;cursor:pointer;font:inherit}
.grokbot-home__chief strong{display:block;font-size:20px;font-weight:600}.grokbot-home__chief small{display:block;font-size:14px;color:var(--gk-text-2);margin-top:7px}
.grokbot-home__arrow{display:grid;place-items:center;margin-left:auto;width:44px;height:44px;border-radius:50%;background:var(--gk-text);color:var(--gk-bg);font-size:25px;flex:none;transition:transform .18s ease-out}.grokbot-home__chief:hover .grokbot-home__arrow{transform:translateX(3px)}
.grokbot-home__section{display:flex;align-items:center;justify-content:space-between;margin:22px 0 14px;color:var(--gk-text-2);font-size:13px}.grokbot-home__textlink{border:0;background:transparent;cursor:pointer;color:var(--gk-text-2);font:inherit;font-size:12px;min-height:40px;padding:8px 0}
.grokbot-home .grokbot-home__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px 34px;max-width:none;width:100%}
.grokbot-home__member{display:flex;align-items:center;gap:14px;min-height:72px;padding:8px 10px 8px 0;border:0;border-radius:10px;background:transparent;color:inherit;text-align:left;cursor:pointer;min-width:0;font:inherit;transition:background .18s}
.grokbot-home__member:hover{background:var(--gk-bg-soft)}.grokbot-home__member>span:last-child{min-width:0}.grokbot-home__member strong{display:block;font-size:15px;font-weight:600}.grokbot-home__member small{display:block;font-size:12px;line-height:1.6;color:var(--gk-text-2);margin-top:5px;overflow-wrap:anywhere}
.grokbot-home__utilities{display:flex;gap:24px;margin-top:44px}.grokbot-home__utilities button{font:inherit;font-size:12px;color:var(--gk-text-2);border:0;background:transparent;min-height:40px;cursor:pointer;padding:0}.grokbot-home :focus-visible{outline:2px solid var(--gk-text);outline-offset:4px}
.grokbot-brand{margin-right:auto;font:inherit;font-size:21px;font-weight:750;letter-spacing:-.7px;color:var(--gk-text);border:0;background:transparent;cursor:pointer;min-height:44px;padding:0 6px}.gk-rail .grokbot-brand{display:none}
.gk-permissions{padding:32px;box-sizing:border-box;overflow:auto;height:100%;max-width:900px;margin:0 auto;color:var(--gk-text)}.gk-permissions h1{font-size:26px}.gk-permissions p{font-size:14px;line-height:1.8;color:var(--gk-text-2)}.gk-permissions article{padding:20px 0;border-bottom:1px solid var(--gk-line)}.gk-permissions header{display:flex;justify-content:space-between;align-items:center}.gk-permissions small{display:block;overflow-wrap:anywhere;font-size:12px;color:var(--gk-text-2);line-height:1.8}.gk-permissions pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;background:var(--gk-bg-soft);padding:14px;border-radius:8px}.gk-permissions button{font:inherit;font-size:13px;min-height:40px;background:transparent;border:1px solid var(--gk-line);border-radius:8px;color:inherit;padding:6px 12px;cursor:pointer}
@media(max-width:650px){.grokbot-home{padding:44px 24px}.grokbot-home .grokbot-home__grid{gap:12px;grid-template-columns:1fr}.grokbot-home__sub{margin-bottom:24px!important}.grokbot-home__chief{gap:12px}}
@media(prefers-reduced-motion:reduce){.grokbot-home__arrow,.grokbot-home__member{transition:none}.grokbot-home__chief:hover .grokbot-home__arrow{transform:none}}
`
